import {
 Folder,
 Home,
 Car,
 Utensils,
 Heart,
 Book,
 Gamepad2,
 ShoppingBag,
 Briefcase,
 Laptop,
 TrendingUp,
 Plus,
 MoreHorizontal,
 Zap,
 Wifi,
 Phone,
 Tv,
 Music,
 Camera,
 Gift,
 Plane,
 MapPin,
 Coffee,
 Pizza,
 Shirt,
 Dumbbell,
 Stethoscope,
 GraduationCap,
 // Adicionados para a Sidebar
 LayoutDashboard,
 CreditCard,
 Tags,
 BarChart3,
 Settings,
 Target,
 HelpCircle,
 Wallet,
 type LucideIcon,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
 folder: Folder,
 home: Home,
 car: Car,
 utensils: Utensils,
 heart: Heart,
 book: Book,
 "gamepad-2": Gamepad2,
 "shopping-bag": ShoppingBag,
 briefcase: Briefcase,
 laptop: Laptop,
 "trending-up": TrendingUp,
 plus: Plus,
 "more-horizontal": MoreHorizontal,
 zap: Zap,
 wifi: Wifi,
 phone: Phone,
 tv: Tv,
 music: Music,
 camera: Camera,
 gift: Gift,
 plane: Plane,
 "map-pin": MapPin,
 coffee: Coffee,
 pizza: Pizza,
 shirt: Shirt,
 dumbbell: Dumbbell,
 stethoscope: Stethoscope,
 "graduation-cap": GraduationCap,
 // Adicionados para a Sidebar
 "layout-dashboard": LayoutDashboard,
 "credit-card": CreditCard,
 tags: Tags,
 "bar-chart-3": BarChart3,
 settings: Settings,
 target: Target,
 "help-circle": HelpCircle,
 wallet: Wallet,
}

export const availableIcons = Object.keys(iconMap)

export function getIconComponent(iconName: string): LucideIcon {
 return iconMap[iconName] || Folder
}